package.path = "storefront.koplugin/?.lua;" .. package.path

local storefront_utils = require("storefront_utils")

describe("storefront_utils", function()
    describe("softWrapLongTokens", function()
        it("wraps tokens exceeding max length", function()
            local input = "short token_that_is_very_long_and_exceeds_the_default_maximum_length_limit"
            local result = storefront_utils.softWrapLongTokens(input, 20)
            assert.is_string(result)
            assert.truthy(result:find("\n"))
        end)

        it("handles empty or short input without modification", function()
            assert.are.same("", storefront_utils.softWrapLongTokens(""))
            assert.are.same("hello world", storefront_utils.softWrapLongTokens("hello world", 20))
        end)
    end)

    describe("normalizeMetaPath", function()
        it("normalizes meta paths correctly", function()
            assert.are.same("_meta.lua", storefront_utils.normalizeMetaPath("_meta.lua"))
            assert.are.same("plugins/my_plugin.koplugin/_meta.lua", storefront_utils.normalizeMetaPath("plugins/my_plugin.koplugin/_meta.lua"))
            assert.are.same("my_plugin.koplugin/_meta.lua", storefront_utils.normalizeMetaPath("my_plugin"))
        end)

        it("handles nil and empty strings", function()
            assert.is_nil(storefront_utils.normalizeMetaPath(nil))
            assert.is_nil(storefront_utils.normalizeMetaPath(""))
        end)
    end)

    describe("sanitizeMetaPath", function()
        it("returns normalized primary path when present", function()
            assert.are.same("test.koplugin/_meta.lua", storefront_utils.sanitizeMetaPath("test"))
        end)

        it("falls back to fallback path when primary path is nil/empty", function()
            assert.are.same("fallback.koplugin/_meta.lua", storefront_utils.sanitizeMetaPath("", "fallback"))
        end)
    end)

    describe("firstNonEmpty", function()
        it("returns first non-nil, non-empty value", function()
            assert.are.same("found", storefront_utils.firstNonEmpty(nil, "", "found", "other"))
            assert.are.same(123, storefront_utils.firstNonEmpty(nil, 123, "text"))
        end)

        it("returns nil when all inputs are empty or nil", function()
            assert.is_nil(storefront_utils.firstNonEmpty(nil, "", nil))
        end)
    end)

    describe("isVersionNewer", function()
        it("compares semver-style version strings correctly", function()
            assert.is_true(storefront_utils.isVersionNewer("1.2.0", "1.1.9"))
            assert.is_true(storefront_utils.isVersionNewer("v2.0.0", "1.9.9"))
            assert.is_false(storefront_utils.isVersionNewer("1.0.0", "1.0.0"))
            assert.is_false(storefront_utils.isVersionNewer("1.0.0", "1.1.0"))
        end)

        it("returns false for invalid inputs", function()
            assert.is_false(storefront_utils.isVersionNewer(nil, "1.0.0"))
            assert.is_false(storefront_utils.isVersionNewer("1.0.0", nil))
        end)
    end)

    describe("normalizeDescription", function()
        it("returns valid descriptions and filters function memory strings", function()
            assert.are.same("A nice plugin", storefront_utils.normalizeDescription("A nice plugin"))
            assert.are.same("", storefront_utils.normalizeDescription("function: 0x12345678"))
            assert.are.same("", storefront_utils.normalizeDescription(123))
        end)
    end)

    describe("parseGitHubTimestamp", function()
        it("parses ISO 8601 timestamp strings to os.time integers", function()
            local ts = storefront_utils.parseGitHubTimestamp("2026-07-29T12:00:00Z")
            assert.is_number(ts)
            assert.is_true(ts > 0)
        end)

        it("returns 0 for invalid inputs", function()
            assert.are.same(0, storefront_utils.parseGitHubTimestamp(nil))
            assert.are.same(0, storefront_utils.parseGitHubTimestamp("invalid"))
        end)
    end)

    describe("repoStarsValue", function()
        it("extracts star count from repo object or data field", function()
            assert.are.same(42, storefront_utils.repoStarsValue({ stars = 42 }))
            assert.are.same(99, storefront_utils.repoStarsValue({ data = { stargazers_count = 99 } }))
            assert.are.same(0, storefront_utils.repoStarsValue(nil))
        end)
    end)

    describe("repoIsFork", function()
        it("detects fork status from repo object or data field", function()
            assert.is_true(storefront_utils.repoIsFork({ fork = true }))
            assert.is_true(storefront_utils.repoIsFork({ data = { fork = true } }))
            assert.is_false(storefront_utils.repoIsFork({ fork = false }))
            assert.is_false(storefront_utils.repoIsFork(nil))
        end)
    end)
end)
